### ISSUE TITLE
Magui, from citellus can do run citellus analisys remotely and do report status

### ISSUE THREAD

**Issue by iranzo** [zerodayz/meles#1]
Hi,
Magui at https://github.com/zerodayz/citellus can do run ansible to collect data (in this case citellus execution) on remote hosts and grab the resulting file for analisys.

Regards!
Pablo

**Comment by zerodayz** [comment]
Yes I saw in https://review.gerrithub.io/#/c/394904/ but it requires ansible-playbook. This is simple SSH and it doesn't run the citellus.json but collects sosreport. Maybe we could make a shell script version of the ansible playbook?
